openapi: 3.1.0
info:
  title: Aiera Events API
  description: API for accessing events data from Aiera
  version: 1.0.0
servers:
  - url: https://premium.aiera.com/api
security:
  - ApiKeyAuth: []
paths:
  /transcrippets:
    get:
        security:
          - ApiKeyAuth: []
        operationId: getEventTranscripts
        description: Retrieves a transcrippet url.
        summary: Retrieves a transcrippet url according to the parameters.
        parameters:
          - name: transcrippet_id
            in: query
            required: false
            schema:
              type: integer
            description: ID of the transcrippet.
          - name: event_id
            in: query
            required: false
            schema:
              type: integer
            description: ID of the event.
          - name: equity_id
            in: query
            required: false
            schema:
              type: integer
            description: ID of the equity.
          - name: speaker_id  
            in: query
            required: false
            schema:
              type: integer
            description: ID of the speaker.
          - name : transcript_item_id
            in: query
            required: false
            schema:
              type: integer
            description: ID of the transcript item.
          - name: created_start_date
            in: query
            required: false
            schema:
              type: string
            description: Fetch events on or after this date (defaults to 2 weeks ago)
          - name: created_end_date  
            in: query
            required: false
            schema:
              type: string
            description: Fetch events on or before this date (defaults to 2 weeks from now)
        responses:
          "200":
            description: Successfully retrieved the transcrippets
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Transcrippet"
          "default":
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"        

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:

    Transcrippet:
      type: object
      properties:
        trimmed_audio_url:
          type: string
          format: url

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
